#!/usr/bin/env python
"""Differential checks for OpenCL Q5_1 SOA GET_ROWS indexing."""

from __future__ import annotations

import random
import unittest
from pathlib import Path

QK5_1 = 32
Q5_1_BYTES = 16


def pack_block(values: list[int]) -> tuple[bytes, int]:
    assert len(values) == QK5_1
    assert all(0 <= value < 32 for value in values)
    qs = bytes((values[i] & 0x0F) | ((values[i + 16] & 0x0F) << 4) for i in range(16))
    qh = sum(((value >> 4) & 1) << i for i, value in enumerate(values))
    return qs, qh


def noshuffle(qs: bytes) -> bytes:
    out = bytearray(Q5_1_BYTES)
    for i in range(8):
        x0 = qs[2 * i]
        x1 = qs[2 * i + 1]
        out[i] = (x0 & 0x0F) | ((x1 & 0x0F) << 4)
        out[i + 8] = ((x0 & 0xF0) >> 4) | (x1 & 0xF0)
    return bytes(out)


def extract_q4(packed: int, t: int, transposed: bool) -> int:
    if transposed:
        return packed & 0x0F
    return (packed >> (4 * (t >> 4))) & 0x0F


def decode_generic(qs_plane: bytes, qh_plane: list[int], row: int, blocks: int, ind: int) -> int:
    t = ind % QK5_1
    block = ind // QK5_1
    block_index = row * blocks + block
    packed = qs_plane[block_index * Q5_1_BYTES + (t & 15)]
    q = extract_q4(packed, t, transposed=False)
    return q | (((qh_plane[block_index] >> t) & 1) << 4)


def decode_transposed(qs_words: list[int], qh_bytes: bytes, row: int, rows: int, ind: int) -> int:
    t = ind % QK5_1
    block = ind // QK5_1
    qh = sum(qh_bytes[(4 * block + byte) * rows + row] << (8 * byte) for byte in range(4))
    word_col = 8 * block + 4 * (t >> 4) + ((t & 15) >> 2)
    word = qs_words[word_col * rows + row]
    packed = word >> (4 * (t & 3))
    q = extract_q4(packed, t, transposed=True)
    return q | (((qh >> t) & 1) << 4)


class Q51GetRowsLayoutTest(unittest.TestCase):
    def test_embedded_header_matches_kernel_source(self) -> None:
        root = Path(__file__).resolve().parents[1]
        source = (root / "ggml/src/ggml-opencl/kernels/get_rows.cl").read_text(encoding="utf-8")
        embedded = (root / "ggml/src/ggml-opencl/autogenerated/get_rows.cl.h").read_text(encoding="utf-8")
        expected = "".join(f'R\"({line})\"\n' for line in source.splitlines(keepends=True))
        self.assertEqual(expected, embedded)

    def test_transposed_support_requires_original_contiguous_geometry(self) -> None:
        root = Path(__file__).resolve().parents[1]
        source = (root / "ggml/src/ggml-opencl/ggml-opencl.cpp").read_text(encoding="utf-8")
        support_case = source[source.index("case GGML_TYPE_Q5_1:"):source.index("#else", source.index("case GGML_TYPE_Q5_1:"))]

        required_guards = (
            "extra->physical_ne00 == op->src[0]->ne[0]",
            "extra->physical_ne01 == op->src[0]->ne[1]",
            "op->src[0]->ne[2] == 1",
            "op->src[0]->ne[3] == 1",
            "ggml_is_contiguous(op->src[0])",
        )
        for guard in required_guards:
            self.assertIn(guard, support_case)

    def test_generic_and_adreno_transposed_layouts_match_aos(self) -> None:
        rng = random.Random(0x51)
        rows = 7
        blocks = 5
        source = [[[rng.randrange(32) for _ in range(QK5_1)] for _ in range(blocks)] for _ in range(rows)]

        packed = [[pack_block(source[row][block]) for block in range(blocks)] for row in range(rows)]
        qs_plane = b"".join(packed[row][block][0] for row in range(rows) for block in range(blocks))
        qh_plane = [packed[row][block][1] for row in range(rows) for block in range(blocks)]

        words_by_row: list[list[int]] = []
        qh_bytes_by_row: list[bytes] = []
        for row in range(rows):
            words: list[int] = []
            qh_bytes = bytearray()
            for block in range(blocks):
                shuffled = noshuffle(packed[row][block][0])
                words.extend(shuffled[i] | (shuffled[i + 1] << 8) for i in range(0, Q5_1_BYTES, 2))
                qh_bytes.extend(packed[row][block][1].to_bytes(4, "little"))
            words_by_row.append(words)
            qh_bytes_by_row.append(bytes(qh_bytes))

        qs_words = [words_by_row[row][column] for column in range(blocks * 8) for row in range(rows)]
        qh_bytes = bytes(
            qh_bytes_by_row[row][column]
            for column in range(blocks * 4)
            for row in range(rows)
        )

        for row in range(rows):
            for ind in range(blocks * QK5_1):
                expected = source[row][ind // QK5_1][ind % QK5_1]
                self.assertEqual(expected, decode_generic(qs_plane, qh_plane, row, blocks, ind))
                self.assertEqual(expected, decode_transposed(qs_words, qh_bytes, row, rows, ind))


if __name__ == "__main__":
    unittest.main()
